-- Generated by import_workers_from_rh_xlsx.js
BEGIN;

-- Ensure UNASSIGNED exists
INSERT INTO teams(id, name, chef_id)
VALUES ('UNASSIGNED', 'Non affectés', NULL)
ON CONFLICT (id) DO NOTHING;

-- UPSERT workers from RH file (rolePrincipal = Utilisateur)
INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_gourdin.sophie',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Adélaïde GROS' LIMIT 1), 'UNASSIGNED'),
  'Sophie GOURDIN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_henry.Jade',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Adélaïde GROS' LIMIT 1), 'UNASSIGNED'),
  'Jade HENRY',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_vandekerckhove.philippe',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Georges D''HAENE' LIMIT 1), 'UNASSIGNED'),
  'Philippe VANDEKERCKHOVE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_vanwonterghem.jérôme',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Georges D''HAENE' LIMIT 1), 'UNASSIGNED'),
  'Jérôme VANWONTERGHEM',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_vecchio.claudio',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Adélaïde GROS' LIMIT 1), 'UNASSIGNED'),
  'Claudio VECCHIO',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_aslan.zeliha',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Sylvain DASSONVILLE' LIMIT 1), 'UNASSIGNED'),
  'Zeliha ASLAN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_poullain.emeline',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Elodie DELESALLE' LIMIT 1), 'UNASSIGNED'),
  'Emeline POULLAIN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_vanderperre.lorelei',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Philippe GREMBER' LIMIT 1), 'UNASSIGNED'),
  'Lorelei VANDERPERRE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_addarraz.mohamed',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Philippe GREMBER' LIMIT 1), 'UNASSIGNED'),
  'Mohamed ADDARRAZ',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_delannoy.delphine',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Sylvain DASSONVILLE' LIMIT 1), 'UNASSIGNED'),
  'Delphine DELANNOY',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_zerfaoui.samia',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Sylvain DASSONVILLE' LIMIT 1), 'UNASSIGNED'),
  'Samia ZERFAOUI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_jouvenaux.coralie',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Elodie DELESALLE' LIMIT 1), 'UNASSIGNED'),
  'Coralie JOUVENAUX',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_kleyn.emilie',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Elodie DELESALLE' LIMIT 1), 'UNASSIGNED'),
  'Emilie KLEYN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_devliegher.juliette',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Elodie DELESALLE' LIMIT 1), 'UNASSIGNED'),
  'Juliette DEVLIEGHER',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_catillon.léane',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Elodie DELESALLE' LIMIT 1), 'UNASSIGNED'),
  'Léane CATILLON',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_lelong.léa',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Elodie DELESALLE' LIMIT 1), 'UNASSIGNED'),
  'Léa LELONG',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_bourabia.nassera',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Sylvain DASSONVILLE' LIMIT 1), 'UNASSIGNED'),
  'Nassera BOURABIA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_abdous.khaled',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Djamel MOKRAOUI' LIMIT 1), 'UNASSIGNED'),
  'Khaled ABDOUS',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_akimien.sylvain',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Jordan DELRUE' LIMIT 1), 'UNASSIGNED'),
  'Sylvain AKIMIEN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_alali.ibrahim',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'Ibrahim AL ALI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_avadanei.cerestin',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Cerestin AVADANEI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_ba.mamoud',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Mamoud BA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_balog.marek',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Marek BALOG',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_barcsa.Jeno',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Jeno BARCSA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_bastin.jeanmichel',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Jordan DELRUE' LIMIT 1), 'UNASSIGNED'),
  'Jean-Michel BASTIN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_bejzaku.devcet',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'William VANDEKERCKHOVE' LIMIT 1), 'UNASSIGNED'),
  'Devcet BEJZAKU',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_borcsa.iancu',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Iancu BORCSA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_borreman.Brandon',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Georges D''HAENE' LIMIT 1), 'UNASSIGNED'),
  'Brandon BORREMAN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_bouabdallah.yacine',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Jordan DELRUE' LIMIT 1), 'UNASSIGNED'),
  'Yacine BOUABDALLAH',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_boussadia.nasir',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Reynald SCHROEYERS' LIMIT 1), 'UNASSIGNED'),
  'Nasir BOUSSADIA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_bouve.Brandon',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Kamal ABDELLAOUI' LIMIT 1), 'UNASSIGNED'),
  'Brandon BOUVE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_bouve.jordy',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Jordy BOUVE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_cartigny.anthony',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Djamel MOKRAOUI' LIMIT 1), 'UNASSIGNED'),
  'Anthony CARTIGNY',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_chaachou.Nabil',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'Nabil CHAACHOU',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_choquet.bernard',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Bernard CHOQUET',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_christiaens.christophe',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Georges D''HAENE' LIMIT 1), 'UNASSIGNED'),
  'Christophe CHRISTIAENS',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_croitoru.Silviu-Stefan',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Silviu-Stefan CROITORU',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_darras.Virginie',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Djamel MOKRAOUI' LIMIT 1), 'UNASSIGNED'),
  'Virginie DARRAS',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_dauvergne.alexandre',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Abdoulaye BAH' LIMIT 1), 'UNASSIGNED'),
  'Alexandre DAUVERGNE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_delourme.nicolas',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Georges D''HAENE' LIMIT 1), 'UNASSIGNED'),
  'Nicolas DELOURME',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_demeulemeester.olivier',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Olivier DEMEULEMESSTER',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_demian.petru',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Petru DEMIAN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_demolin.david',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Mohamed OUKAS' LIMIT 1), 'UNASSIGNED'),
  'David DEMOLIN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_dumazy.amory',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Amory DUMAZY',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_duponcheel.cedric',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Cédric DUPONCHEEL',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_elgarni.ahcene',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Reynald SCHROEYERS' LIMIT 1), 'UNASSIGNED'),
  'Ahcene ELGARNI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_gadenne.philippe',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Philippe GADENNE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_gaoua.Samir',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Samir GAOUA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_gaspar.gimi',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Gimi GASPAR',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_ghestin.Joeffrey',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'Joeffrey GHESTIN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_ghilmanou.saphir',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Reynald SCHROEYERS' LIMIT 1), 'UNASSIGNED'),
  'Saphir GHILMANOU',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_goncalves.manuel',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Kamal ABDELLAOUI' LIMIT 1), 'UNASSIGNED'),
  'Manuel GONCALVES',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_guilbert.christian',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Christian GUILBERT',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_hamimi.farid',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Farid HAMIMI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_hego.cédric',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Cédric HEGO',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_herteler.mathilde',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Mathilde HERTELER',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_iabbadene.kamel',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Mohamed OUKAS' LIMIT 1), 'UNASSIGNED'),
  'Kamel IABBADENE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_lacatusu.simona',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Reynald SCHROEYERS' LIMIT 1), 'UNASSIGNED'),
  'Simona LACATUSU',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_laib.mourad',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Mourad LAIB',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_lingurar.andor',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Abdoulaye BAH' LIMIT 1), 'UNASSIGNED'),
  'Andor LINGURAR',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_lingurar.augustin',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Abdoulaye BAH' LIMIT 1), 'UNASSIGNED'),
  'Augustin LINGURAR',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_maquet.catherine',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Abdoulaye BAH' LIMIT 1), 'UNASSIGNED'),
  'Catherine MAQUET',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_martocean.sanda-ramona',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Djamel MOKRAOUI' LIMIT 1), 'UNASSIGNED'),
  'Sanda-Ramona MARTOCEAN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_micola.remus',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Remus MICOLA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_mohamedjimale.abdirizak',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Azzedine RARBI' LIMIT 1), 'UNASSIGNED'),
  'Abdirizak MOHAMED JIMALE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_moldovan.moise',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Moise MOLDOVAN',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_mondry.Aurélie',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Adélaïde GROS' LIMIT 1), 'UNASSIGNED'),
  'Aurélie MONDRY',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_moulana.ahmed',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Ahmed MOULANA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_neamt.claudiu',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'Claudiu NEAMT',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_ouahabi.abderrezak',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Abdoulaye BAH' LIMIT 1), 'UNASSIGNED'),
  'Abderrezak OUAHABI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_phle.then-vang',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'William VANDEKERCKHOVE' LIMIT 1), 'UNASSIGNED'),
  'Then-Vang PHLE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_picher.Mickaël',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Georges D''HAENE' LIMIT 1), 'UNASSIGNED'),
  'Mickaël PICHER',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_puichault.maxime',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Reynald SCHROEYERS' LIMIT 1), 'UNASSIGNED'),
  'Maxime PUICHAULT',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_rabia.laurent',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Jordan DELRUE' LIMIT 1), 'UNASSIGNED'),
  'Laurent RABIA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_raveleau.julien',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Julien RAVELEAU',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_rohart.stive',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Reynald SCHROEYERS' LIMIT 1), 'UNASSIGNED'),
  'Stive ROHART',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_rostas.daniela',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Daniela ROSTAS',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_simon.julien',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Adélaïde GROS' LIMIT 1), 'UNASSIGNED'),
  'Julien SIMON',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_staelens.jonathan',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'William VANDEKERCKHOVE' LIMIT 1), 'UNASSIGNED'),
  'Jonathan STAELENS',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_stoica.manuel-sorin',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'William VANDEKERCKHOVE' LIMIT 1), 'UNASSIGNED'),
  'Manuel-Sorin STOICA',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_taraiour.elhassane',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'El Hassane TARAIOUR',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_tounsi.amar',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Antoine MORTIER' LIMIT 1), 'UNASSIGNED'),
  'Amar TOUNSI',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_traore.toumani',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'Toumani TRAORE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_vanbrugge.christelle',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Kamal ABDELLAOUI' LIMIT 1), 'UNASSIGNED'),
  'Christelle VANBRUGGE',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_wachter.raoel',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Samuel DELEPIERRE' LIMIT 1), 'UNASSIGNED'),
  'Raoel WACHTER',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_weldab.mengs',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Hamid URRICH' LIMIT 1), 'UNASSIGNED'),
  'Mengs WELDAB',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  'w_zemour.djilali',
  COALESCE((SELECT id FROM teams WHERE chef_id = 'Djamel MOKRAOUI' LIMIT 1), 'UNASSIGNED'),
  'Djilali ZEMOUR',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;

COMMIT;
