// api/scripts/import_workers_from_rh_xlsx.js
import fs from "fs";
import path from "path";
import xlsx from "xlsx";

const input = process.argv[2];
if (!input) {
  console.log('Usage: node api/scripts/import_workers_from_rh_xlsx.js "chemin/fichier.xlsx"');
  process.exit(1);
}

function escSql(s) {
  if (s === null || s === undefined) return "";
  return String(s).replace(/'/g, "''").trim();
}

function normLogin(s) {
  return String(s || "").trim();
}

const wb = xlsx.readFile(input);
const sheetName = wb.SheetNames[0];
const sheet = wb.Sheets[sheetName];
const rows = xlsx.utils.sheet_to_json(sheet, { defval: "" });

// Filtre: uniquement Utilisateur
const users = rows.filter((r) => String(r.rolePrincipal).trim() === "Utilisateur");

// Génération SQL
const outPath = path.resolve(process.cwd(), "import_workers.sql");

let sql = "";
sql += "-- Generated by import_workers_from_rh_xlsx.js\n";
sql += "BEGIN;\n\n";

sql += `-- Ensure UNASSIGNED exists\n`;
sql += `INSERT INTO teams(id, name, chef_id)\n`;
sql += `VALUES ('UNASSIGNED', 'Non affectés', NULL)\n`;
sql += `ON CONFLICT (id) DO NOTHING;\n\n`;

sql += "-- UPSERT workers from RH file (rolePrincipal = Utilisateur)\n";

let count = 0;

for (const r of users) {
  const login = normLogin(r.login);
  if (!login) continue;

  const firstName = escSql(r.firstName);
  const lastName = escSql(r.lastName);
  const manager = normLogin(r.manager);

  const workerId = `w_${login}`;
  const fullName = escSql(`${firstName} ${lastName}`.trim());

  // team_id résolu par chef_id = manager, sinon UNASSIGNED
  const teamIdExpr = manager
    ? `COALESCE((SELECT id FROM teams WHERE chef_id = '${escSql(manager)}' LIMIT 1), 'UNASSIGNED')`
    : `'UNASSIGNED'`;

  sql += `
INSERT INTO workers (
  id, team_id, name, employee_number, role, attendance, status, controlled, last_check_at
) VALUES (
  '${escSql(workerId)}',
  ${teamIdExpr},
  '${fullName || escSql(login)}',
  NULL,
  NULL,
  'PRESENT',
  'OK',
  false,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  name = EXCLUDED.name;
`.trim();

  sql += "\n\n";
  count++;
}

sql += "COMMIT;\n";

fs.writeFileSync(outPath, sql, "utf-8");

console.log(`✅ SQL généré: ${outPath}`);
console.log(`➡️  Utilisateurs importables (rolePrincipal=Utilisateur): ${users.length}`);
console.log(`➡️  Statements workers générés: ${count}`);